@startuml
!theme plain
top to bottom direction
skinparam linetype ortho
skinparam classAttributeIconSize 0

title Class Diagram - Importer module

class ElasticConfig {
  + ElasticConfig(): 
  - url: String
  + elasticsearchClient(RestClient): ElasticsearchClient
  + setUrl(String): void
  + restClient(): RestClient
  + getUrl(): String
}
class ElasticsearchClient_Importer {
  + ElasticsearchClient_Importer(ElasticsearchClient, RestClient): 
  - restClient: RestClient
  + esClient: ElasticsearchClient
  + close(): void
  + bulkIndexWithContext(InputStream, String): void
}
class ImporterApplication {
  + ImporterApplication(): 
  + main(String[]): void
}
class ImporterController {
  + ImporterController(ImporterService): 
  - importerService: ImporterService
  + hello(): String
  + getStatus(String): ResponseEntity<String>
  + import_indexFile(MultipartFile, String): ResponseEntity<String>
}
class ImporterService {
  + ImporterService(ElasticsearchClient_Importer): 
  - elasticsearchClientIndexer: ElasticsearchClient_Importer
  - jobStatus: Map<String, String>
  + indexArticles(File, String, String): void
  + getJobStatus(String): String
}
class OpenApiConfig {
  + OpenApiConfig(): 
  + customOpenAPI(): OpenAPI
}

ImporterController           "1" *-[#595959,plain]-> "importerService\n1" ImporterService              
ImporterService              "1" *-[#595959,plain]-> "elasticsearchClientIndexer\n1" ElasticsearchClient_Importer
@enduml
