

services:


  #-----------------------------------------------------
  # OWILIX — extracts raw index data into ./dataset/public/main
  #----------------------------------------------------
  owilix:
    build:
      context: .
      dockerfile: ./owi/Dockerfile
    image: my_owilix
    volumes:
      - ./all_data/raw_data:/app/all_data/.owi
      - ./all_data:/app/all_data
    working_dir: /app
    environment:
      HOME: /app/all_data
      OWI_PATH: /app/all_data/
      OWI_AUTH_METHOD: device
      PY4LEXYS_AUTH_METHOD: device
      USE_DEVICE_FLOW: "true"
    restart: unless-stopped
