services:

#-----------------------------------------------------
# OWILIX — Container used to download and filter OWI-related datasets
#-----------------------------------------------------
  owilix:
    build: 
      context: ./owi
      dockerfile: Dockerfile
    container_name: owilix
    image: owilix
    volumes:
      - ./all_data/raw_data:/app/all_data/.owi
      - ./all_data:/app/all_data
    working_dir: /app
    environment:
      HOME: /app/all_data
      OWI_PATH: /app/all_data/
      OWI_AUTH_METHOD: device
      PY4LEXYS_AUTH_METHOD: device
      USE_DEVICE_FLOW: "true"
    networks:
      - softPlat-network
    restart: no


#-----------------------------------------------------
# INFERER — Topic Modeling Toolkit
#-----------------------------------------------------
  inferer:
    container_name: inferer
    image: inferer
    build:
      context: ./inferer
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    networks:
      - softPlat-network


#-----------------------------------------------------
# MONGODB — Database that stores documents in BSON format
#-----------------------------------------------------
  mongodb:
    image: mongo:8.2.2-noble
    container_name: mongodb
    networks:
      - softPlat-network
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })'" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always


#-----------------------------------------------------
# ELASTICSEARCH — Single-node Elasticsearch's instance with disabled security features and persistent storage for indexed data.
#-----------------------------------------------------
  elasticsearch:
    container_name: elasticsearch
    image: elastic/elasticsearch:9.1.8
    ports:
      - 9200:9200
    networks: 
      - softPlat-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data


#-----------------------------------------------------
# SEARCHER — Spring's project app (REST).
#-----------------------------------------------------
  searcher:
    container_name: searcher
    image: searcher
    build:
      context: ./searcher
      dockerfile: Dockerfile
    ports:
      - 8881:8881
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - softPlat-network


#-----------------------------------------------------
# IMPORTER — Spring's project app (REST).
#-----------------------------------------------------
  importer:
    container_name: importer
    image: importer
    build:
      context: ./importer
      dockerfile: Dockerfile
    ports:
      - 8882:8882
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - softPlat-network

 
#-----------------------------------------------------
# NGINX — Reverse proxy for UI.
#-----------------------------------------------------  
 
  nginx:
    container_name: proxy-nginx
    image: nginx:1.29-alpine
    volumes:
      - ./nginx/static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - searcher
    networks:
      - softPlat-network
      

volumes:
  mongodb-volume:
  elasticsearch-volume:

networks:
  softPlat-network:
