@startuml
!theme plain
top to bottom direction
skinparam linetype ortho
skinparam classAttributeIconSize 0

interface DocService << interface >> {
  + infer(Document): Document
  + inferBatch(List<Document>): List<Document>
}
class DocServiceImpl {
  + DocServiceImpl(): 
  - topicTopWords: Map<Integer, String>
  - model: ParallelTopicModel
  + infer(Document): Document
  + inferBatch(List<Document>): List<Document>
  + init(): void
  - loadModel(): ParallelTopicModel
}
class Document {
  + Document(String, String, String, String, String): 
  + Document(): 
  - main_content: String
  - id: String
  - title: String
  - topics: String
  - url: String
  + hashCode(): int
  + getUrl(): String
  + setTitle(String): void
  + getTopic(): String
  + equals(Object): boolean
  + getMain_content(): String
  + setMain_content(String): void
  + getId(): String
  + setId(String): void
  + getTitle(): String
  + setUrl(String): void
  + setTopic(String): void
}
class InfererApplication {
  + InfererApplication(): 
  + main(String[]): void
}
class InfererController {
  + InfererController(DocServiceImpl): 
  - docService: DocService
  + inferTopics(Document): Document
  + hello(): String
  + inferBatchTopics(List<Document>): List<Document>
}
class JsonInferencerService {
  + JsonInferencerService(): 
  - loadPipe(): Pipe
  + computeTopicTopWords(ParallelTopicModel, int): Map<Integer, String>
  - argMax(double[]): int
  + inferPrevalentTopicJsonl(TopicInferencer, Document, Map<Integer, String>): Document
}
class OpenApiConfig {
  + OpenApiConfig(): 
  + customOpenAPI(): OpenAPI
}

DocServiceImpl         -[#008200,dashed]-^  DocService            
InfererController     "1" *-[#595959,plain]-> "docService\n1" DocService
@enduml
