server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Home route of the application: it redirects you to the search web page (index.html). If not it returns error 403
    location / {
        try_files $uri $uri/ =403;
    }


    # Set of test endpoints to test if the services are up and running correctly
    location /api/v1/importer/hello {
            proxy_pass http://importer:8882/api/v1/importer/hello;
    }


    location /api/v1/searcher/hello {
                proxy_pass http://searcher:8881/api/v1/searcher/hello;
    }
    # end of test endpoints -----------------------------------


    # Importer endpoint: max supported import's file size: 2GB
    location /api/v1/importer/import {
        proxy_pass http://importer:8882/api/v1/importer/import;

        client_max_body_size 2G;

        limit_except POST {
            deny all;
        }
    }

    # Searcher endpoint to perform the research on the pages
    location /api/v1/searcher/search {
        proxy_pass http://searcher:8881/api/v1/searcher/search;
    }


    # importer endpoint to get the dataset importing status
    location /api/v1/importer/status/ {
        proxy_pass http://importer:8882/api/v1/importer/status/;
    }


    # Access the Documentation Portal here: http://localhost/docs/
    location /docs {
    	proxy_pass http://swagger-ui:8080/;
    }

    # endpoint for swagger to fetch searcher docs
    location /docs/api-docs/searcher {
            proxy_pass http://searcher:8881/v3/api-docs;
    }

    # endpoint for swagger to fetch importer docs
    location /docs/api-docs/importer {
        proxy_pass http://importer:8882/v3/api-docs;
    }

    # endpoint for swagger to fetch inferer docs
    location /docs/api-docs/inferer {
        proxy_pass http://inferer:5050/v3/api-docs;
    }
}

