# Costruzione e running del container:
# Da dentro la cartella con il dockerfile e il file .sh
# docker buildx build -t owi-ubuntu .
# docker run --name ubuntuOwi -p 8008:8008 -v pathHost:/app/data -it owi-ubuntu /bin/bash 

# Per eseguirlo se già attivo:
# docker exec -it nomeContainer bash

#ESEMPIO PRATICO COMANDI DA ESEGUIRE UNA VOLTA DENTRO:
# root@b516f4d1208f:/app/data# source /opt/conda/bin/activate 
# (base) root@b516f4d1208f:/app/data# conda activate owi
# (owi) root@b516f4d1208f:/app/data# owilix remote pull all/internalID=3fad40fc-c68b-11f0-a6f8-f6a03915313d

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Installa le dipendenze per owi cli
RUN apt-get update && apt-get install -y \
    wget \
    bash \
    curl \
    git \
    vim \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Installa Miniconda
RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
    && bash miniconda.sh -b -p /opt/conda \
    && rm miniconda.sh

# Aggiungi conda al PATH
ENV PATH=/opt/conda/bin:$PATH

# Copia ed esegui lo script di installazione
COPY installazioneOwi.sh /tmp/installazioneOwi.sh
RUN chmod +x /tmp/installazioneOwi.sh && /tmp/installazioneOwi.sh

# Imposta il PATH per includere l'ambiente owi (se c'è solo questo nel container)
# ENV PATH=/opt/conda/envs/owi/bin:$PATH

# Crea directory per i dati
RUN mkdir -p /app/data /app/config

# ------------------- per Mosaic --------------
RUN apt-get update && apt-get install -y \
    openjdk-21-jdk \
    maven \
    && apt-get clean

# Imposta JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

# Se solo Mosaic nel container
#ENV PATH="$JAVA_HOME/bin:$PATH"

# PATH per mosaic + conda per owi-cli
ENV PATH="$JAVA_HOME/bin:/opt/conda/envs/owi/bin:$PATH"
#-----------------------------------


# Forza device flow authentication
ENV OWILIX_AUTH_METHOD=device
ENV PY4LEXIS_AUTH_METHOD=device
ENV USE_DEVICE_FLOW=true

# Per settare il path di OWI in una cartella personalizzata e non in ~/.owi
ENV OWS_OWI_PATH = /app/data/{access}
# oppure: owilix config set owi_path /app/data/

WORKDIR /app/data

CMD ["bash"]
