@startuml

skinparam sequenceParticipant underline 
skinparam {
  ' Overall style
  FontSize 14

  ' Colors
  ArrowColor #000000
  ArrowFontColor #000000
  BackgroundColor #FFFFFF
  BorderColor #DEDEDE
  FontColor #333333

  ' Participant styling
  Participant {
    BorderColor #0077B6
    BackgroundColor #F0F8FF
    FontColor #005691
  }

  ' Actor styling
  Actor {
    BorderColor #6A057F
    BackgroundColor #F5EEF8
    FontColor #510363
  }

  ' Sequence specific
  Sequence {
    ArrowThickness 2
    LifeLineBorderColor #444444
    LifeLineBackgroundColor #F7F7F7
    BoxBorderColor #AAAAAA
    BoxBackgroundColor #FFFFFF
    BoxFontColor #333333
  }
}
title Importer module - Sequence diagram

actor Client

participant "ImporterController" as Controller
participant "ImporterService" as Service
participant "ElasticsearchClient_Importer" as Importer
participant "ElasticsearchClient" as ESClient


== Upload NDJSON File ==
Client -> Controller : POST /api/v1/importer/import\nfile + indexName
activate Controller

Controller -> Service : indexArticles(file, indexName, jobId)
activate Service
Service -> Service : assign job status "IN_PROGRESS"\ngenerate jobId

Service -> Importer : bulkIndexWithContext(file, indexName)
activate Importer
Importer -> Importer : check if index exists\ncreate if not

Importer -> ESClient : indices().exists(indexName)
activate ESClient
ESClient --> Importer : boolean
deactivate ESClient

alt Index does not exist
    Importer -> ESClient : indices().create(indexName)
    activate ESClient
    ESClient --> Importer : acknowledgement
    deactivate ESClient
end

loop read NDJSON line by line
    Importer -> Importer : validate JSON
    Importer -> ESClient : ingester.add(doc)

    activate ESClient
    ESClient --> Importer : acknowledgement
    deactivate ESClient
end
Importer --> Service: void


deactivate Importer
Service -> Controller : return "Import started. Job ID: {jobId}"
deactivate Service

Controller --> Client : HTTP 200 OK
deactivate Controller

== Check Job Status ==
Client -> Controller : GET /api/v1/importer/status/{jobId}
activate Controller

Controller -> Service : getJobStatus(jobId)
activate Service
Service -> Service : lookup job status

Service --> Controller : return job status
deactivate Service

Controller --> Client : HTTP 200 OK / 404 Not Found
deactivate Controller
@enduml

