spring.application.name=indexer
server.port=8882

spring.servlet.multipart.max-file-size=5000MB
spring.servlet.multipart.max-request-size=5000MB
spring.servlet.multipart.resolve-lazily=true
elasticsearch.server.url=http://elasticsearch:9200

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=true