spring.application.name=searcher
server.port=8881
inferer.base-url=http://inferer:5050/api/v1/inferBatch
elasticsearch.server.url=http://elasticsearch:9200

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=true